// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivfvrmgnjyikuyfurcpu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2ZnZybWduanlpa3V5ZnVyY3B1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MTM3ODcsImV4cCI6MjA2MDM4OTc4N30.MbCjIrzSnmIgtvH5VQXVnRpeoZS6GgUU0W4qpLG1qnM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);